### ISSUE TITLE
Media ingest API incorrectly sets visibility to 0

### ISSUE THREAD

**Issue by elv-serban** [eluv-io/elv-client-js#135]
Noticed in testing that the visibility of objects changes after running an ingest process (specifically mezzanine prep of an existing mezzanine object).  Likely done for historical reasons that no longer apply.  This is not expected and should not be done.

As a side node I don't believe it would be useful to add flags for permissions setting in the media ingest API and tool at this version but once / if content creation API takes permissions arguments, then ingesting a new object could take these parameters and pass them down to the content creation API.

**Comment by eponymous301** [comment]
fixed in https://github.com/eluv-io/elv-client-js/commit/77246021ba0decb0dbe7eda8471d6d6b330e7c08
