### ISSUE TITLE
Add a download method to get video or audio in mp4 files for a given time period

### ISSUE THREAD

**Issue by elv-haoyu** [eluv-io/elv-client-js#295]
The existing download url method works for content with `hls-clear` offering. We need a generic method to download either the video or audio content for a specific time period. 

Input argument: `content iq` or `content hash`, `start_time` (in float of seconds), `end_time` (in float of seconds), `stream` (video or audio) 
steps: 
- Get content metadata, get parts based on the start and end time
- Use ffmpeg to crop and concatenate parts and output `.mp4` 
- Follow the existing download url method naming convention, e.g. `Title - Gloucester vs Clermont MEZ (1920x1080) (00-07-11 - 00-08-06).mp4`, i.e., `Title - {display_title} ({resolution}) ({start_time} - {end_time}).mp4`

The method should trim the start and end time if they are outside the actual duration of the entire content.

**Comment by elv-preethi** [comment]
PR #296
